const INPUT_ACTION = {
  NONE: 'NONE',
  RUNNING: 'RUNNING',
  LOOKING_UP: 'LOOKING_UP',
  LOOKING_DOWN: 'LOOKING_DOWN',
  DASHING: 'DASHING',
  SWORD_FORWARD: 'SWORD_FORWARD',
  SWORD_UP: 'SWORD_UP',
  SWORD_DOWN: 'SWORD_DOWN',
  GUN_FORWARD: 'GUN_FORWARD',
  GUN_UP: 'GUN_UP',
  GUN_DOWN: 'GUN_DOWN',
} as const;

export { INPUT_ACTION };
