const INPUT_ACTION = {
  NONE: 'NONE',
  RUN: 'RUN',
  DASH: 'DASH',
  JUMP: 'JUMP',
  LOOK_UP: 'LOOK_UP',
  LOOK_DOWN: 'LOOK_DOWN',
  LONG_ATTACK_UP: 'LONG_ATTACK_UP',
  LONG_ATTACK_DOWN: 'LONG_ATTACK_DOWN',
  LONG_ATTACK_FORWARD: 'LONG_ATTACK_FORWARD',
  SHORT_ATTACK_UP: 'SHORT_ATTACK_UP',
  SHORT_ATTACK_DOWN: 'SHORT_ATTACK_DOWN',
  SHORT_ATTACK_FORWARD: 'SHORT_ATTACK_FORWARD',
} as const;

export { INPUT_ACTION };
