export const GRAVITY = 1300;
export const CHARACTER_SPEED_X = 100;
export const CHARACTER_SPEED_Y = 450;
export const CHARACTER_HEALTH = 100;
export const DEFAULT_CHARACTER_LIVES = 10;
export const DEFAULT_CHARACTER_INVENCIBILITY_TIME = 1000;
