const CHARACTER_STATE = {
  RUN: 'RUN',
  IDLE: 'IDLE',
  DEAD: 'DEAD',
  HEAD: 'HEAD',
  JUMP: 'JUMP',
  SLICE: 'SLICE',
  LOOK_UP: 'LOOK_UP',
  LOOK_DOWN: 'LOOK_DOWN',
  DEAD_NO_HEAD: 'DEAD_NO_HEAD',
  LONG_ATTACK_UP: 'LONG_ATTACK_UP',
  LONG_ATTACK_DOWN: 'LONG_ATTACK_DOWN',
  LONG_ATTACK_FORWARD: 'LONG_ATTACK_FORWARD',
  SHORT_ATTACK_UP: 'SHORT_ATTACK_UP',
  SHORT_ATTACK_DOWN: 'SHORT_ATTACK_DOWN',
  SHORT_ATTACK_FORWARD: 'SHORT_ATTACK_FORWARD',
} as const;

export { CHARACTER_STATE };
