const CHARACTER_STATES = [
  'IDLE',
  'DEAD',
  'HEAD',
  'RUNNING',
  'JUMPING',
  'SLICING',
  'LOOKING_UP',
  'LOOKING_DOWN',
  'DEAD_NO_HEAD',
  'LONG_ATTACKING_UP',
  'LONG_ATTACKING_DOWN',
  'LONG_ATTACKING_FORWARD',
  'SHORT_ATTACKING_UP',
  'SHORT_ATTACKING_DOWN',
  'SHORT_ATTACKING_FORWARD',
] as const;

export { CHARACTER_STATES };
