name: Create PR Summary

on:
  pull_request:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-slim

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout To PR Code
        uses: actions/checkout@v4

      - name: Fetch PR Diff
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            console.log('pr.data.diff_url:', pr.data.diff_url);

            try {
              const response = await fetch(pr.data.diff_url);

              if (!response.ok) console.log('No PR Diff found', response);

              const pr_diff = await response.json();

              console.log('pr_diff', pr_diff);
            } catch (error) {
                throw new Error('Error fetching PR Diff:', error.message);
             }
